
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  ssl_certificate: ssl/fullchain.pem
  ssl_key: ssl/privkey.pem
  base_url: https://268d01731307.sn.mynetname.net:8123
  
#Others
zone: !include include/zones.yaml
discovery:
history: !include include/history.yaml
yandex_smart_home: !include yandex_smart_home.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

#mqtt:
#  broker: a0d7b954-mqtt
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  client_id: home-assistant
  
homekit:
  autostart: false
  
#recorder:
#  purge_interval: 1
#  purge_keep_days: 7
  
stream:
camera:
#  - platform: generic
#    name: Example
#    still_image_url: https://www.home-assistant.io/images/default-social.png
#    stream_source: rtsp://flussonic.powernet.com.ru:554/user81415
media_player:
  - platform: philips_js
    host: 192.168.88.56
    api_version: 5
