- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
#    - type: disk_use_percent
#      arg: /mnt/home-media
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'